data_ingestion:
  data_url: https://raw.githubusercontent.com/Himanshu-1703/reddit-sentiment-analysis/refs/heads/main/data/reddit.csv
  test_size: 0.2
  data_path: data


model_trainer:
  trained_model_path: models/trained_model.pkl
  vectorizer_path: models/tfidf_vectorizer.pkl
  max_features: 1000
  ngram_range: [1, 3]
  learning_rate: 0.09
  max_depth: 20
  n_estimators: 367


model_evaluator:
   root_dir: ""
   metric_output_path: evaluation_info
   acceptance_threshold: 0.7
   mlflow_tracking_uri: http://ec2-13-245-159-214.af-south-1.compute.amazonaws.com:5000/
   mlflow_experiment_name: dvc-pipeline-runs